---
title: "PATHS"
author: "Gabe Rice, Jawaria Jaleel, Nicole Nguyen, Perla Guzman, and Mohamed Salem"
date: "2024-07-3"
output: html_document
---
# introduction
hello this is going to be a document listing and showing some of our findings in the datasheets.


# You Gov datasheet


```{r setup, include=FALSE}
# Load necessary libraries and data
library(tidyverse)
load("../data/yougov_ideology.RData")
classify_yougov <- read_csv("../data/classify_yougov.csv")

```

```{r}
# Prepare the data for analysis
yougov_join <- yougov_ideology %>% 
  select(person_id, q12_ideology, slant) %>%
  distinct() 

explore_yougov <- classify_yougov %>% 
  left_join(yougov_join, by="person_id")
```

```{r}
# How many people are in the dataset?
total_people <- yougov_ideology %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
total_people

```

```{r}
# How many people have visited fake news sources?
fake_news_visitors <- explore_yougov %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
fake_news_visitors

# Calculate the proportion of fake news visitors
fake_news_proportion <- fake_news_visitors / total_people
fake_news_proportion

# Number of non-fake news visitors
non_fake_news_visitors <- total_people - fake_news_visitors
non_fake_news_visitors
```

```{r}
# Political affiliation counts
# Total left
total_left <- yougov_ideology %>% 
  filter(slant == 'left') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
total_left

# Total right
total_right <- yougov_ideology %>% 
  filter(slant == 'right') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
total_right

# Total neutral
total_neutral <- yougov_ideology %>% 
  filter(slant == 'neutral') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
total_neutral

```

```{r}

# Visit counts by political affiliation
# Left visits
left_visits <- explore_yougov %>% 
  filter(slant == 'left') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
left_visits

# Right visits
right_visits <- explore_yougov %>% 
  filter(slant == 'right') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
right_visits

# Neutral visits
neutral_visits <- explore_yougov %>% 
  filter(slant == 'neutral') %>% 
  summarise(unique_ids = n_distinct(person_id)) %>% 
  pull(unique_ids)
neutral_visits

```

```{r}
# Distribution of site types visited by neutral affiliation
neutral_distribution <- explore_yougov %>% 
  filter(slant == "neutral", !is.na(label)) %>% 
  group_by(label) %>% 
  tally()
neutral_distribution

# Top visited site by neutral affiliation
top_neutral_site <- explore_yougov %>% 
  filter(slant == "neutral", label == "right bias") %>% 
  group_by(domain) %>% 
  summarise(visits = n()) %>% 
  arrange(desc(visits))
top_neutral_site

```

```{r}
# Top fake news visitor in left wing
top_left_fake_news_visitor <- explore_yougov %>% 
  filter(!is.na(label), slant == "left") %>% 
  group_by(person_id) %>% 
  summarise(visits = n()) %>% 
  arrange(desc(visits)) %>% 
  head(1)
top_left_fake_news_visitor

# Distribution of site types visited by left affiliation
left_distribution <- explore_yougov %>% 
  filter(slant == "left", !is.na(label)) %>% 
  group_by(label) %>% 
  tally()
left_distribution

# Top visited site by left affiliation
top_left_site <- explore_yougov %>% 
  filter(slant == "left", label == "fake") %>% 
  group_by(domain) %>% 
  tally()
top_left_site

```

```{r}
# Distribution of site types visited by right affiliation
right_distribution <- explore_yougov %>% 
  filter(slant == "right", !is.na(label)) %>% 
  group_by(label) %>% 
  tally()
right_distribution

# Top visited site by right affiliation
top_right_site <- explore_yougov %>% 
  filter(slant == "right", label == "fake") %>% 
  group_by(domain) %>% 
  summarise(visits = n()) %>% 
  arrange(desc(visits))
top_right_site

```


```{r}
# Create a dataframe for plotting total vs fake news visitors
plot_data_total_vs_fake <- tibble(
  category = c("Total People", "Fake News Visitors"),
  count = c(total_people, fake_news_visitors)
)

ggplot(plot_data_total_vs_fake, aes(x = category, y = count, fill = category)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(title = "Total Number of People vs. Fake News Visitors", 
       x = "Category", 
       y = "Number of People") +
  theme_minimal() +
  scale_fill_manual(values = c("Total People" = "blue", "Fake News Visitors" = "red")) +
  geom_text(aes(label = count), vjust = -0.5)

```


```{r}
# Plot 2: Proportion of Fake News Visitors
proportion_data <- tibble(
  category = c("Fake News Visitors", "Non-Fake News Visitors"),
  count = c(fake_news_visitors, non_fake_news_visitors)
)

ggplot(proportion_data, aes(x = "", y = count, fill = category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  labs(title = "Proportion of Fake News Visitors", 
       x = "", 
       y = "Number of People") +
  theme_minimal() +
  scale_fill_manual(values = c("Fake News Visitors" = "red", "Non-Fake News Visitors" = "blue")) +
  geom_text(aes(label = count), position = position_stack(vjust = 0.5))

```

```{r}
# Plot 3: Political Affiliation Counts
plot_data_affiliation <- yougov_ideology %>%
  filter(slant %in% c("left", "right", "neutral", "na")) %>%
  group_by(slant) %>%
  summarise(count = n_distinct(person_id))

ggplot(plot_data_affiliation, aes(x = slant, y = count, fill = slant)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(title = "Political Affiliation Counts", 
       x = "Affiliation", 
       y = "Number of People") +
  theme_minimal() +
  scale_fill_manual(values = c("left" = "blue", "right" = "red", "neutral" = "grey", "na" = 'black')) +
  geom_text(aes(label = count), vjust = -0.5)



```

```{r}
# Plot 4: Visits by Political Affiliation
plot_data_visits <- explore_yougov %>%
  filter(slant %in% c("left", "right", "neutral")) %>%
  group_by(slant) %>%
  summarise(count = n_distinct(person_id))

ggplot(plot_data_visits, aes(x = slant, y = count, fill = slant)) +
  geom_bar(stat = "identity", width = 0.5) +
  labs(title = "Visits by Political Affiliation", 
       x = "Affiliation", 
       y = "Number of People") +
  theme_minimal() +
  scale_fill_manual(values = c("left" = "blue", "right" = "red", "neutral" = "grey")) +
  geom_text(aes(label = count), vjust = -0.5)


```



